/* Generated By:JJTree: Do not edit this line. JoNodeQuote.java */

package lang.jo.parser;

public class JoNodeQuote extends SimpleNode {
  public JoNodeQuote(int id) {
    super(id);
  }

  public JoNodeQuote(JoParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JoNodeQuote(id);
  }

  public static Node jjtCreate(JoParser p, int id) {
      return new JoNodeQuote(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JoParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
