/* Generated By:JJTree: Do not edit this line. JoNodeIdentifier.java */

package lang.jo.parser;

public class JoNodeIdentifier extends SimpleNode {
  public JoNodeIdentifier(int id) {
    super(id);
  }

  public JoNodeIdentifier(JoParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JoNodeIdentifier(id);
  }

  public static Node jjtCreate(JoParser p, int id) {
      return new JoNodeIdentifier(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JoParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
