/* Generated By:JJTree: Do not edit this line. JoNodeArgument.java */

package lang.jo.parser;

public class JoNodeArgument extends SimpleNode {
  public JoNodeArgument(int id) {
    super(id);
  }

  public JoNodeArgument(JoParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JoNodeArgument(id);
  }

  public static Node jjtCreate(JoParser p, int id) {
      return new JoNodeArgument(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JoParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
