/* Generated By:JJTree: Do not edit this line. JoNodeMessage.java */

package lang.jo.parser;

public class JoNodeMessage extends SimpleNode {
  public JoNodeMessage(int id) {
    super(id);
  }

  public JoNodeMessage(JoParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JoNodeMessage(id);
  }

  public static Node jjtCreate(JoParser p, int id) {
      return new JoNodeMessage(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JoParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
