/* Generated By:JJTree: Do not edit this line. JoNodeOperator.java */

package lang.jo.parser;

public class JoNodeOperator extends SimpleNode {
  public JoNodeOperator(int id) {
    super(id);
  }

  public JoNodeOperator(JoParser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
      return new JoNodeOperator(id);
  }

  public static Node jjtCreate(JoParser p, int id) {
      return new JoNodeOperator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(JoParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
