/* Generated By:JJTree&JavaCC: Do not edit this line. JoParserConstants.java */
package lang.jo.parser;

public interface JoParserConstants {

  int EOF = 0;
  int OPERATOR = 1;
  int ASSIGN = 2;
  int GT = 3;
  int LT = 4;
  int BANG = 5;
  int HOOK = 6;
  int TILDE = 7;
  int PLUS = 8;
  int MINUS = 9;
  int STAR = 10;
  int SLASH = 11;
  int BACKSLASH = 12;
  int BIT_AND = 13;
  int BIT_OR = 14;
  int XOR = 15;
  int REM = 16;
  int ATMARK = 17;
  int DLR = 18;
  int SEMICOLON = 19;
  int COLON = 20;
  int DOT = 21;
  int TERMINATOR = 22;
  int SEPERATOR = 23;
  int WHITESPACE = 24;
  int SCTPAD = 25;
  int SCPAD = 26;
  int WCPAD = 27;
  int NEWLINE = 28;
  int COMMA = 29;
  int IDENTIFIER = 30;
  int LETTER = 31;
  int SPECIALCHAR = 32;
  int NUMBER = 33;
  int HEXNUMBER = 34;
  int DECIMAL = 35;
  int OCTET = 36;
  int FLOAT = 37;
  int EXPONENT = 38;
  int COMMENT = 39;
  int SINGLE_LINE_COMMENT = 40;
  int MULTI_LINE_COMMENT = 41;
  int BACKQUOTES = 42;
  int SINGLEQUOTES = 43;
  int DOUBLEQUOTES = 44;
  int TRIQUOTES = 45;
  int BACK_QUOTE = 46;
  int SINGLE_QUOTE = 47;
  int DOUBLE_QUOTE = 48;
  int TRI_QUOTE = 49;
  int B_WITH_STRING = 50;
  int S_WITH_STRING = 51;
  int D_WITH_STRING = 52;
  int T_WITH_STRING = 53;
  int NOT_MULTI_LINE = 54;
  int ESCAPE_SEQUENCE = 55;
  int OPEN = 56;
  int LPAREN = 57;
  int LBRACE = 58;
  int LBRACKET = 59;
  int CLOSE = 60;
  int RPAREN = 61;
  int RBRACE = 62;
  int RBRACKET = 63;
  int ANYTHING_ELSE = 64;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<OPERATOR>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"?\"",
    "\"~\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\\\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"@\"",
    "\"$\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "<TERMINATOR>",
    "<SEPERATOR>",
    "<WHITESPACE>",
    "<SCTPAD>",
    "<SCPAD>",
    "<WCPAD>",
    "<NEWLINE>",
    "\",\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIALCHAR>",
    "<NUMBER>",
    "<HEXNUMBER>",
    "<DECIMAL>",
    "<OCTET>",
    "<FLOAT>",
    "<EXPONENT>",
    "<COMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<BACKQUOTES>",
    "<SINGLEQUOTES>",
    "<DOUBLEQUOTES>",
    "<TRIQUOTES>",
    "\"`\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\"\\\"\\\"\"",
    "<B_WITH_STRING>",
    "<S_WITH_STRING>",
    "<D_WITH_STRING>",
    "<T_WITH_STRING>",
    "<NOT_MULTI_LINE>",
    "<ESCAPE_SEQUENCE>",
    "<OPEN>",
    "\"(\"",
    "\"{\"",
    "\"[\"",
    "<CLOSE>",
    "\")\"",
    "\"}\"",
    "\"]\"",
    "<ANYTHING_ELSE>",
  };

}
