/* Generated By:JJTree: Do not edit this line. ./JoParserTreeConstants.java */

package lang.jo.parser;

public interface JoParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTMESSAGE = 1;
  public int JJTVOID = 2;
  public int JJTARGUMENT = 3;
  public int JJTIDENTIFIER = 4;
  public int JJTNUMBER = 5;
  public int JJTOPERATOR = 6;
  public int JJTQUOTE = 7;


  public String[] jjtNodeName = {
    "Expression",
    "Message",
    "void",
    "Argument",
    "Identifier",
    "Number",
    "Operator",
    "Quote",
  };
}
