/* Generated By:JJTree: Do not edit this line. ./JoParserVisitor.java */

package lang.jo.parser;

public interface JoParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(JoNodeExpression node, Object data);
  public Object visit(JoNodeMessage node, Object data);
  public Object visit(JoNodeArgument node, Object data);
  public Object visit(JoNodeIdentifier node, Object data);
  public Object visit(JoNodeNumber node, Object data);
  public Object visit(JoNodeOperator node, Object data);
  public Object visit(JoNodeQuote node, Object data);
}
